use template literal on some few places
markedjs/marked pull request #2419
Opened 2022-03-26 23:02 UTC by jimmywarting

**Marked version:**

**Markdown flavor:** Markdown.pl|CommonMark|GitHub Flavored Markdown|n/a

## Description

- Fixes #### (if fixing a known issue; otherwise, describe issue using the following format)

## Contributor

- [ ] Test(s) exist to ensure functionality and minimize regression (if no tests added, list tests covering this PR); or,
- [ ] no tests required for this PR.
- [ ] If submitting new feature, it has been documented in the appropriate places.

## Committer

In most cases, this should be a different person than the contributor.

- [ ] CI is green (no forced merge required).
- [ ] Squash and Merge PR following [conventional commit guidelines](https://www.conventionalcommits.org/).

2022-03-30 04:59 UTC, UziTech requested changes

2022-03-30 04:59 UTC, UziTech commented on src/Renderer.js
> +      ? `<${type} align="${flags.align}">'`
```suggestion
      ? `<${type} align="${flags.align}">`
```

2022-03-30 05:03 UTC, calculuschild commented
Do template literals cause any noticeable slowdown?

2022-03-30 05:41 UTC, UziTech commented
I don't see any difference when running `npm run bench` on master or this PR.

2022-04-02 17:34 UTC, styfle approved these changes
Thanks!

2022-04-02 21:45 UTC, merged