Update USING_PRO.md
markedjs/marked pull request #3492
Opened 2024-10-17 18:51 UTC by linuxbckp

Add document about #3487

2024-10-18 23:21 UTC, linuxbckp commented
OK. I changed to Marked part.

2024-10-20 03:14 UTC, UziTech requested changes

2024-10-20 03:14 UTC, UziTech commented on docs/USING_ADVANCED.md
> +Another case is, if you want to rerun function everytime they open a file, or you want to make marked.run() non-state, you can create a new instance of Marked to ensure options and extensions are loc
It doesn't seem like this is saying anything more than the documentation above. That the user should use Marked instance if they want extensions to be locally scoped.

I think the example should emphasize that `marked.use(...)` should not be used in a loop or function. It should only be used directly after `new Marked` is created or `marked` is imported

2024-10-20 03:52 UTC, linuxbckp commented
OK. I changed to a note.

2024-10-20 05:17 UTC, UziTech approved these changes
Thanks! 💯

2024-10-20 05:19 UTC, merged